import { StyleSheet, Dimensions } from 'react-native';
import { ColorScheme } from '../../interfaces';

const createStyles = (colors: ColorScheme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingTop: 16,
  },
  gradientSection: {
    marginTop: -16,
    marginHorizontal: -16,
    paddingTop: 16,
    paddingBottom: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    marginBottom: 8,
  },
  alertCardOverride: {
    marginHorizontal: 30,
    marginBottom: 0,
    shadowColor: colors.cardShadow,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 16,
    elevation: 6,
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
    marginBottom: 16,
    gap: 12,
  },
  backButton: {
    flex: 0.35,
    backgroundColor: colors.surface,
    borderRadius: 24,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 3,
  },
  backButtonText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Inter_600SemiBold',
  },
  actionButton: {
    flex: 0.65,
    backgroundColor: colors.surface,
    borderRadius: 24,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: colors.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 3,
  },
  actionButtonIconWrapper: {
    width: 20,
    height: 20,
    borderRadius: 5,
    backgroundColor: colors.success,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionButtonText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Inter_600SemiBold',
  },
  mapCard: {
    padding: 0,
    overflow: 'hidden',
    marginVertical: 8,
  },
  mapLabelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    padding: 12,
    position: 'absolute',
    top: 0,
    left: 0,
    zIndex: 15,
  },
  mapLabel: {
    fontSize: 12,
    color: colors.textSecondary,
    fontWeight: '600',
    fontFamily: 'Inter_600SemiBold',
  },
  mapCanvas: {
    backgroundColor: colors.surfaceSecondary,
    height: 180,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 16,
    position: 'relative',
  },
  gridContainer: {
    ...StyleSheet.absoluteFillObject,
    flexDirection: 'column',
  },
  gridRow: {
    flex: 1,
    flexDirection: 'row',
  },
  gridCell: {
    flex: 1,
    borderWidth: 0.5,
    borderColor: colors.border + '40',
  },
  pinWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  pinGlow: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tooltip: {
    backgroundColor: colors.surfaceSecondary,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginTop: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  tooltipText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: '600',
    fontFamily: 'Inter_600SemiBold',
  },
  sectionHeader: {
    marginTop: 20,
    marginBottom: 8,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
    fontFamily: 'Inter_700Bold',
  },
  sectionSubtitle: {
    fontSize: 11,
    color: colors.textMuted,
    marginTop: 4,
    marginLeft: 26,
    fontFamily: 'Inter_400Regular',
  },
  dataCard: {
    marginVertical: 4,
  },
  dataRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  dataRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  dataRowLabel: {
    fontSize: 14,
    color: colors.textSecondary,
    fontFamily: 'Inter_400Regular',
  },
  dataRowValueContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  dataRowValue: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.primary,
    fontFamily: 'Inter_700Bold',
  },
  dataRowUnit: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textMuted,
    fontFamily: 'Inter_400Regular',
  },
  explanationCard: {
    marginVertical: 4,
    backgroundColor: colors.surface,
  },
  translationText: {
    fontSize: 14,
    color: colors.text,
    lineHeight: 22,
    fontFamily: 'Inter_400Regular',
  },
});

export default createStyles;
